on:
  push:
    branches:
      - master

name: Deploy
jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-18.04
    steps:
      -
        uses: actions/checkout@v2
      -
        name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      -
        name: Install AWS CLI
        run: pip install --upgrade pip awscli
      -
        name: Deploy to AWS CloudFormation
        run: ./scripts/deploy.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SRC_BUCKET_NAME: ${{ secrets.SRC_BUCKET_NAME }}
          STACK_NAME: ${{ secrets.STACK_NAME }}